### ISSUE TITLE
Error in rule splitting

### ISSUE THREAD

**Issue by Valentin-Bio** [samnooij/PathoFact#5]
Hello dear developer, I'm trying to run PathoFact in y HPC. At this point, I have followed the installation tutorial and the usage here specified: https://git-r3lab.uni.lu/laura.denies/PathoFact. 

Once the dependencies were installed, I modified the config.yaml file to run the program for my 8 fasta files coming from the metagenomic assembly.  After that, I ran the snakemake file as recommended in the "Usage" section but I get an arror message (txt file attached) of "Error in rule splitting".

This is my modified version of the yaml file:

```
pathofact:
  sample: ["CC_final.contigs","FL_final.contigs","SJ_final.contigs","ST_final.contigs","DR_final.contigs","SG_final.contigs","SL_final.contigs","TR_final.contigs"] # requires user input
  project: "PathoFact_cecilia" # requires user input
  datadir:  "/home/vberrios/ceci_cosas/contigs_iniciales" # requires user input
  workflow: "complete" #options: "complete", "AMR", "Tox", "Vir"
  size_fasta: 10000 #Adjustable to preference
  scripts: "scripts"
  signalp: "/home/vberrios/signalp-5.0b/bin" # requires user input
  deepvirfinder: "submodules/DeepVirFinder/dvf.py"
  tox_hmm: "databases/toxins/combined_Toxin.hmm"
  tox_lib: "databases/library_HMM_Toxins.csv"
  tox_threshold: 40 #Bitscore threshold of the toxin prediction, adjustable by user to preference
  vir_hmm: "databases/virulence/Virulence_factor.hmm"
  vir_domains: "databases/models_and_domains"
  plasflow_threshold: 0.7
  plasflow_minlen: 1000
  runtime:
    short: "00:10:00"
    medium: "01:00:00"
    long: "02:00:00"
  mem:
    normal_mem_per_core_gb: "4G"
    big_mem_cores: 4
    big_mem_per_core_gb: "30G"
```

Here in this issue, I attach the stdout message when running PathoFact

[pathofact.txt](https://github.com/user-attachments/files/18663213/pathofact.txt)

And finally, here I attach the .sh script I used:

```
#!/usr/bin/bash


#SBATCH --partition=basic
#SBATCH --cpus-per-task=20
#SBATCH --nodelist=n001
#SBATCH --time=10-00:00:00
#SBATCH -J pathfact
#SBATCH -o pathofact.out
#SBATCH -e pathofact.err

module load Miniconda

# activate the env
conda activate PathoFact
# run the pipeline
# set <cores> to the number of cores to use, e.g. 10
snakemake -s Snakefile --use-conda --reason --cores 20 -p

```
